from sqlalchemy import Column, String, String, Float, Boolean, Text, Date, TIMESTAMP, JSON, Integer
from sqlalchemy.orm import declarative_base
from datetime import datetime

Base = declarative_base()


class User(Base):
    __tablename__ = "Users"
    id = Column(String, primary_key=True)
    username = Column(String, nullable=True)
    email = Column(String, unique=True, nullable=True)
    role = Column(String, nullable=True)


class Vehicle(Base):
    __tablename__ = "Vehicles"
    project_code = Column(String, nullable=True)
    vehicle_serial_number = Column(String, primary_key=True)
    vehicle_body_number = Column(String, nullable=True)
    vehicle_model = Column(String, nullable=True)
    vehicle_build_level = Column(String, nullable=True)
    transmission_type = Column(String, nullable=True)
    final_drive_axle_ratio = Column(String, nullable=True)
    domain = Column(String, nullable=True)
    tyre_make = Column(String, nullable=True)
    tyre_size = Column(String, nullable=True)
    tyre_pressure_front = Column(Float, nullable=True)
    tyre_pressure_rear = Column(Float, nullable=True)
    tyre_run_in = Column(Float, nullable=True)
    engine_run_in = Column(Float, nullable=True)
    gearbox_run_in = Column(Float, nullable=True)
    axle_run_in = Column(Float, nullable=True)
    engine_oil_specification = Column(String, nullable=True)
    axle_oil_specification = Column(String, nullable=True)
    transmission_oil_specification = Column(String, nullable=True)
    wd_type = Column(String, nullable=True)
    driven_wheel = Column(String, nullable=True)
    intercooler_location = Column(String, nullable=True)
    gear_ratio_1 = Column(String, nullable=True)
    gear_ratio_2 = Column(String, nullable=True)
    gear_ratio_3 = Column(String, nullable=True)
    gear_ratio_4 = Column(String, nullable=True)
    gear_ratio_5 = Column(String, nullable=True)
    reverse_gear_ratio = Column(String, nullable=True)
    department = Column(String, nullable=True)
    id_of_creator = Column(String, nullable=True)
    name_of_creator = Column(String, nullable=True)
    created_on = Column(TIMESTAMP, nullable=True)
    id_of_updater = Column(String, nullable=True)
    name_of_updater = Column(String, nullable=True)
    updated_on = Column(TIMESTAMP, nullable=True)
    vehicle_kerb_weight = Column(String, nullable=True)
    vehicle_gvw = Column(String, nullable=True)
    kerb_faw = Column(String, nullable=True)
    kerb_raw = Column(String, nullable=True)
    awd_rwd_fwd = Column(String, nullable=True)


class Engine(Base):
    __tablename__ = "Engines"
    id = Column(Integer, primary_key=True, autoincrement=True)
    engine_serial_number = Column(String, nullable=True)
    motor_serial_number = Column(String, nullable=True)
    engine_domain = Column(String, nullable=True)
    vehicle_body_number = Column(String, nullable=True)
    project_code = Column(String, nullable=True)
    engine_build_level = Column(String, nullable=True)
    engine_capacity = Column(Float, nullable=True)
    engine_type = Column(String, nullable=True)
    number_of_cylinders = Column(String, nullable=True)
    compression_ratio = Column(Float, nullable=True)
    bore_mm = Column(Float, nullable=True)
    stroke_mm = Column(Float, nullable=True)
    vacuum_modulator_make = Column(String, nullable=True)
    vacuum_modulator_details = Column(String, nullable=True)
    ecu_make = Column(String, nullable=True)
    ecu_id_number = Column(String, nullable=True)
    ecu_dataset_number = Column(String, nullable=True)
    ecu_dataset_details = Column(String, nullable=True)
    injector_type = Column(String, nullable=True)
    turbo_charger_type = Column(String, nullable=True)
    blow_by_recirculation = Column(Boolean, nullable=True)
    nozzle_hole_count = Column(String, nullable=True)
    nozzle_through_flow = Column(Float, nullable=True)
    egr_valve_make = Column(String, nullable=True)
    egr_valve_type = Column(String, nullable=True)
    egr_valve_diameter_mm = Column(Float, nullable=True)
    egr_cooler_make = Column(String, nullable=True)
    egr_cooler_capacity_kw = Column(Float, nullable=True)
    catcon_make = Column(String, nullable=True)
    catcon_type = Column(String, nullable=True)
    catcon_loading = Column(String, nullable=True)
    dpf_make = Column(String, nullable=True)
    dpf_capacity = Column(String, nullable=True)
    scr_make = Column(String, nullable=True)
    scr_capacity = Column(String, nullable=True)
    acc_compressor = Column(Boolean, nullable=True)
    acc_compressor_details = Column(String, nullable=True)
    ps_pump = Column(String, nullable=True)
    ps_details = Column(String, nullable=True)
    water_bypass = Column(String, nullable=True)
    kerb_weight_faw_kg = Column(Float, nullable=True)
    kerb_weight_raw_kg = Column(Float, nullable=True)
    emission_status = Column(String, nullable=True)
    thermostat_details = Column(String, nullable=True)
    vehicle_serial_number = Column(String, nullable=True)
    engine_family = Column(String, nullable=True)
    hv_battery_make = Column(String, nullable=True)
    hv_battery_capacity = Column(Float, nullable=True)
    hv_battery_voltage = Column(Float, nullable=True)
    hv_battery_current = Column(Float, nullable=True)
    ev_motor_power_kw = Column(Float, nullable=True)
    motor_make = Column(String, nullable=True)
    motor_front = Column(Boolean, nullable=True)
    motor_rear = Column(Boolean, nullable=True)
    front_motor_serial_number = Column(String, nullable=True)
    rear_motor_serial_number = Column(String, nullable=True)
    front_motor_max_power = Column(Float, nullable=True)
    rear_motor_max_power = Column(Float, nullable=True)
    front_motor_max_torque = Column(Float, nullable=True)
    rear_motor_max_torque = Column(Float, nullable=True)
    front_motor_make = Column(String, nullable=True)
    rear_motor_make = Column(String, nullable=True)
    motor_max_voltage = Column(Float, nullable=True)
    battery_capacity_kwh = Column(Float, nullable=True)
    battery_max_voltage = Column(Float, nullable=True)
    battery_max_current = Column(Float, nullable=True)
    department = Column(String, nullable=True)
    id_of_creator = Column(String, nullable=True)
    name_of_creator = Column(String, nullable=True)
    created_on = Column(TIMESTAMP, nullable=True)
    id_of_updater = Column(String, nullable=True)
    name_of_updater = Column(String, nullable=True)
    updated_on = Column(TIMESTAMP, nullable=True)


class JobOrder(Base):
    __tablename__ = "JobOrders"
    job_order_id = Column(String, primary_key=True)
    project_code = Column(String, nullable=True)
    vehicle_serial_number = Column(String, nullable=True)
    vehicle_body_number = Column(String, nullable=True)
    engine_serial_number = Column(String, nullable=True)
    CoastDownData_id = Column(String, nullable=True)
    type_of_engine = Column(String, nullable=True)
    department = Column(String, nullable=True)
    domain = Column(String, nullable=True)
    test_status = Column(String, nullable=True)
    completed_test_count = Column(String, nullable=True)
    job_order_status = Column(String, nullable=True)
    id_of_creator = Column(String, nullable=True)
    name_of_creator = Column(String, nullable=True)
    created_on = Column(TIMESTAMP, nullable=True)
    id_of_updater = Column(String, nullable=True)
    name_of_updater = Column(String, nullable=True)
    updated_on = Column(TIMESTAMP, nullable=True)
    cft_members = Column(JSON, nullable=True)

class RDEJobOrder(Base):
    __tablename__ = "RDEJobOrders"
    job_order_id = Column(String, primary_key=True)
    project_code = Column(String, nullable=True)
    vehicle_serial_number = Column(String, nullable=True)
    vehicle_body_number = Column(String, nullable=True)
    engine_serial_number = Column(String, nullable=True)
    CoastDownData_id = Column(String, nullable=True)
    type_of_engine = Column(String, nullable=True)
    department = Column(String, nullable=True)
    domain = Column(String, nullable=True)
    test_status = Column(String, nullable=True)
    completed_test_count = Column(String, nullable=True)
    wbs_code = Column(String, nullable=True)
    vehicle_gwv = Column(String, nullable=True)
    vehicle_kerb_weight = Column(String, nullable=True)
    vehicle_test_payload_criteria = Column(String, nullable=True)
    requested_payload = Column(String, nullable=True)
    idle_exhaust_mass_flow = Column(String, nullable=True)
    job_order_status = Column(String, nullable=True)
    cft_members = Column(JSON, nullable=True)
    id_of_creator = Column(String, nullable=True)
    name_of_creator = Column(String, nullable=True)
    created_on = Column(TIMESTAMP, nullable=True)
    id_of_updater = Column(String, nullable=True)
    name_of_updater = Column(String, nullable=True)
    updated_on = Column(TIMESTAMP, nullable=True)


class TestOrder(Base):
    __tablename__ = "TestOrders"
    test_order_id = Column(String, primary_key=True)
    job_order_id = Column(String, nullable=True)  # removed ForeignKey
    CoastDownData_id = Column(String, nullable=True)         # removed ForeignKey
    coast_down_data = Column(JSON, nullable=True)
    test_type = Column(String, nullable=True)
    engine_number = Column(String, nullable=True)
    test_objective = Column(Text, nullable=True)
    vehicle_location = Column(String, nullable=True)
    cycle_gear_shift = Column(String, nullable=True)
    inertia_class = Column(String, nullable=True)
    dataset_name = Column(String, nullable=True)
    dpf = Column(String, nullable=True)
    dpf_regen_occurs =Column(String, nullable=True)
    dataset_flashed = Column(Boolean, nullable=True)
    ess = Column(String, nullable=True)
    mode = Column(String, nullable=True)
    fuel_type = Column(String, nullable=True)
    hardware_change = Column(Text, nullable=True)
    equipment_required = Column(Text, nullable=True)
    shift = Column(String, nullable=True)
    preferred_date = Column(Date, nullable=True)
    emission_check_date = Column(Date, nullable=True)
    emission_check_attachment = Column(JSON, nullable=True)
    dataset_attachment = Column(JSON, nullable=True)
    a2l_attachment = Column(JSON, nullable=True)
    experiment_attachment = Column(JSON, nullable=True)
    dbc_attachment = Column(JSON, nullable=True)
    wltp_attachment = Column(JSON, nullable=True)
    pdf_report = Column(JSON, nullable=True)
    excel_report = Column(JSON, nullable=True)
    dat_file_attachment = Column(JSON, nullable=True)
    others_attachement = Column(JSON, nullable=True)
    remark = Column(String, nullable=True)
    rejection_remarks = Column(String, nullable=True)
    mail_remarks = Column(String, nullable=True)
    complete_remarks = Column(String, nullable=True)
    specific_instruction = Column(Text, nullable=True)
    status = Column(String, nullable=True)
    id_of_creator = Column(String, nullable=True)
    name_of_creator = Column(String, nullable=True)
    created_on = Column(TIMESTAMP, nullable=True)
    id_of_updater = Column(String, nullable=True)
    name_of_updater = Column(String, nullable=True)
    updated_on = Column(TIMESTAMP, nullable=True)
    updated_on = Column(TIMESTAMP)

class AddFields(Base):
    __tablename__ = "AddFields"
    id = Column(Integer, primary_key=True, autoincrement=True)
    notify_fields = Column(JSON, nullable=True)
    notify_values = Column(JSON, nullable=True)
