"""ADD engine_domain field into Engines table

Revision ID: 32e00ad17289
Revises: c22a0cc84a5d
Create Date: 2025-08-01 12:02:53.060651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32e00ad17289'
down_revision: Union[str, Sequence[str], None] = 'c22a0cc84a5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Engines', sa.Column('engine_domain', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Engines', 'engine_domain')
    # ### end Alembic commands ###
