"""initial schema

Revision ID: 33df2c303525
Revises: 
Create Date: 2025-06-20 15:05:08.303275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33df2c303525'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CoastDownData',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('coast_down_reference', sa.String(), nullable=True),
    sa.Column('vehicle_reference_mass', sa.Float(), nullable=True),
    sa.Column('a_value', sa.Float(), nullable=True),
    sa.Column('b_value', sa.Float(), nullable=True),
    sa.Column('c_value', sa.Float(), nullable=True),
    sa.Column('f0_value', sa.Float(), nullable=True),
    sa.Column('f1_value', sa.Float(), nullable=True),
    sa.Column('f2_value', sa.Float(), nullable=True),
    sa.Column('id_of_creator', sa.String(), nullable=True),
    sa.Column('created_on', sa.TIMESTAMP(), nullable=True),
    sa.Column('id_of_updater', sa.String(), nullable=True),
    sa.Column('updated_on', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Engines',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('engine_serial_number', sa.String(), nullable=True),
    sa.Column('engine_build_level', sa.String(), nullable=True),
    sa.Column('engine_capacity', sa.Float(), nullable=True),
    sa.Column('engine_type', sa.String(), nullable=True),
    sa.Column('number_of_cylinders', sa.String(), nullable=True),
    sa.Column('compression_ratio', sa.Float(), nullable=True),
    sa.Column('bore_mm', sa.Float(), nullable=True),
    sa.Column('stroke_mm', sa.Float(), nullable=True),
    sa.Column('vacuum_modulator_make', sa.String(), nullable=True),
    sa.Column('vacuum_modulator_details', sa.String(), nullable=True),
    sa.Column('ecu_make', sa.String(), nullable=True),
    sa.Column('ecu_id_number', sa.String(), nullable=True),
    sa.Column('ecu_dataset_number', sa.String(), nullable=True),
    sa.Column('ecu_dataset_details', sa.String(), nullable=True),
    sa.Column('injector_type', sa.String(), nullable=True),
    sa.Column('turbo_charger_type', sa.String(), nullable=True),
    sa.Column('blow_by_recirculation', sa.Boolean(), nullable=True),
    sa.Column('nozzle_hole_count', sa.String(), nullable=True),
    sa.Column('nozzle_through_flow', sa.Float(), nullable=True),
    sa.Column('egr_valve_make', sa.String(), nullable=True),
    sa.Column('egr_valve_type', sa.String(), nullable=True),
    sa.Column('egr_valve_diameter_mm', sa.Float(), nullable=True),
    sa.Column('egr_cooler_make', sa.String(), nullable=True),
    sa.Column('egr_cooler_capacity_kw', sa.Float(), nullable=True),
    sa.Column('catcon_make', sa.String(), nullable=True),
    sa.Column('catcon_type', sa.String(), nullable=True),
    sa.Column('catcon_loading', sa.String(), nullable=True),
    sa.Column('dpf_make', sa.String(), nullable=True),
    sa.Column('dpf_capacity', sa.String(), nullable=True),
    sa.Column('scr_make', sa.String(), nullable=True),
    sa.Column('scr_capacity', sa.String(), nullable=True),
    sa.Column('acc_compressor', sa.Boolean(), nullable=True),
    sa.Column('acc_compressor_details', sa.String(), nullable=True),
    sa.Column('ps_pump_location', sa.String(), nullable=True),
    sa.Column('ps_details', sa.String(), nullable=True),
    sa.Column('water_bypass', sa.String(), nullable=True),
    sa.Column('kerb_weight_faw_kg', sa.Float(), nullable=True),
    sa.Column('kerb_weight_raw_kg', sa.Float(), nullable=True),
    sa.Column('emission_status', sa.String(), nullable=True),
    sa.Column('thermostat_details', sa.String(), nullable=True),
    sa.Column('vehicle_id', sa.String(), nullable=True),
    sa.Column('engine_family', sa.String(), nullable=True),
    sa.Column('hv_battery_make', sa.String(), nullable=True),
    sa.Column('hv_battery_capacity', sa.Float(), nullable=True),
    sa.Column('hv_battery_voltage', sa.Float(), nullable=True),
    sa.Column('hv_battery_current', sa.Float(), nullable=True),
    sa.Column('ev_motor_power_kw', sa.Float(), nullable=True),
    sa.Column('id_of_creator', sa.String(), nullable=True),
    sa.Column('created_on', sa.TIMESTAMP(), nullable=True),
    sa.Column('id_of_updater', sa.String(), nullable=True),
    sa.Column('updated_on', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('JobOrders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('vehicle_id', sa.String(), nullable=True),
    sa.Column('engine_id', sa.String(), nullable=True),
    sa.Column('cd_id', sa.String(), nullable=True),
    sa.Column('job_order_number', sa.String(), nullable=True),
    sa.Column('type_of_engine', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('rejection_remarks', sa.String(), nullable=True),
    sa.Column('mail_remarks', sa.String(), nullable=True),
    sa.Column('id_of_creator', sa.String(), nullable=True),
    sa.Column('name_of_creator', sa.String(), nullable=True),
    sa.Column('created_on', sa.TIMESTAMP(), nullable=True),
    sa.Column('id_of_updater', sa.String(), nullable=True),
    sa.Column('name_of_updater', sa.String(), nullable=True),
    sa.Column('updated_on', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('TestOrders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_order_id', sa.String(), nullable=True),
    sa.Column('cd_id', sa.String(), nullable=True),
    sa.Column('test_type', sa.String(), nullable=True),
    sa.Column('test_objective', sa.Text(), nullable=True),
    sa.Column('vehicle_location', sa.String(), nullable=True),
    sa.Column('cycle_gear_shift', sa.String(), nullable=True),
    sa.Column('inertia_class', sa.String(), nullable=True),
    sa.Column('dataset_name', sa.String(), nullable=True),
    sa.Column('dpf', sa.String(), nullable=True),
    sa.Column('dataset_flashed', sa.Boolean(), nullable=True),
    sa.Column('ess', sa.String(), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('hardware_change', sa.Text(), nullable=True),
    sa.Column('equipment_required', sa.Text(), nullable=True),
    sa.Column('shift', sa.String(), nullable=True),
    sa.Column('preferred_date', sa.Date(), nullable=True),
    sa.Column('emission_check_date', sa.Date(), nullable=True),
    sa.Column('emission_check_attachment', sa.Text(), nullable=True),
    sa.Column('specific_instruction', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('id_of_creator', sa.String(), nullable=True),
    sa.Column('name_of_creator', sa.String(), nullable=True),
    sa.Column('created_on', sa.TIMESTAMP(), nullable=True),
    sa.Column('id_of_updater', sa.String(), nullable=True),
    sa.Column('name_of_updater', sa.String(), nullable=True),
    sa.Column('updated_on', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Vehicles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('vehicle_serial_number', sa.String(), nullable=True),
    sa.Column('vehicle_body_number', sa.String(), nullable=True),
    sa.Column('vehicle_model', sa.String(), nullable=True),
    sa.Column('vehicle_number', sa.String(), nullable=True),
    sa.Column('vehicle_build_level', sa.String(), nullable=True),
    sa.Column('transmission_type', sa.String(), nullable=True),
    sa.Column('final_drive_axle_ratio', sa.String(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('coast_down_reference', sa.String(), nullable=True),
    sa.Column('tyre_make', sa.String(), nullable=True),
    sa.Column('tyre_size', sa.String(), nullable=True),
    sa.Column('tyre_pressure_front', sa.Float(), nullable=True),
    sa.Column('tyre_pressure_rear', sa.Float(), nullable=True),
    sa.Column('tyre_run_in_kms', sa.Float(), nullable=True),
    sa.Column('engine_run_in_kms', sa.Float(), nullable=True),
    sa.Column('gearbox_run_in_kms', sa.Float(), nullable=True),
    sa.Column('axle_run_in_kms', sa.Float(), nullable=True),
    sa.Column('engine_oil_spec', sa.String(), nullable=True),
    sa.Column('axle_oil_spec', sa.String(), nullable=True),
    sa.Column('transmission_oil_spec', sa.String(), nullable=True),
    sa.Column('drive_type', sa.String(), nullable=True),
    sa.Column('driven_wheel', sa.String(), nullable=True),
    sa.Column('intercooler_location', sa.String(), nullable=True),
    sa.Column('gear_ratio', sa.String(), nullable=True),
    sa.Column('id_of_creator', sa.String(), nullable=True),
    sa.Column('created_on', sa.TIMESTAMP(), nullable=True),
    sa.Column('id_of_updater', sa.String(), nullable=True),
    sa.Column('updated_on', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Vehicles')
    op.drop_table('Users')
    op.drop_table('TestOrders')
    op.drop_table('JobOrders')
    op.drop_table('Engines')
    op.drop_table('CoastDownData')
    # ### end Alembic commands ###
