"""create a new table AddFields with three columns id,notify_fields json,notify_values json

Revision ID: 3cf62fa2e52d
Revises: 4c5df033233a
Create Date: 2025-08-19 14:54:50.521839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cf62fa2e52d'
down_revision: Union[str, Sequence[str], None] = '4c5df033233a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AddFields',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('notify_fields', sa.JSON(), nullable=True),
    sa.Column('notify_values', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('AddFields')
    # ### end Alembic commands ###
