"""updated test database

Revision ID: 4c5df033233a
Revises: f72f3b09568d
Create Date: 2025-08-14 15:46:25.456912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c5df033233a'
down_revision: Union[str, Sequence[str], None] = 'f72f3b09568d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CoastDownData')
    op.add_column('Engines', sa.Column('name_of_creator', sa.String(), nullable=True))
    op.add_column('Engines', sa.Column('name_of_updater', sa.String(), nullable=True))
    op.add_column('TestOrders', sa.Column('coast_down_data', sa.JSON(), nullable=True))
    op.add_column('Vehicles', sa.Column('name_of_creator', sa.String(), nullable=True))
    op.add_column('Vehicles', sa.Column('name_of_updater', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Vehicles', 'name_of_updater')
    op.drop_column('Vehicles', 'name_of_creator')
    op.drop_column('TestOrders', 'coast_down_data')
    op.drop_column('Engines', 'name_of_updater')
    op.drop_column('Engines', 'name_of_creator')
    op.create_table('CoastDownData',
    sa.Column('CoastDownData_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('job_order_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('coast_down_reference', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('vehicle_reference_mass', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('a_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('b_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('c_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('f0_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('f1_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('f2_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('id_of_creator', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id_of_updater', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('CoastDownData_id', name=op.f('CoastDownData_pkey'))
    )
    # ### end Alembic commands ###
