"""add new column named team in table Users

Revision ID: 5ec265b526ef
Revises: 7911586f68de
Create Date: 2025-08-26 11:33:24.189755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ec265b526ef'
down_revision: Union[str, Sequence[str], None] = '7911586f68de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('team', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'team')
    # ### end Alembic commands ###
