"""create three new columns in TesOrders table name- validated_by(string),validated_on(timestamp),validations_status(string)

Revision ID: 623d55e59aa9
Revises: 3cf62fa2e52d
Create Date: 2025-08-20 15:00:31.372329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '623d55e59aa9'
down_revision: Union[str, Sequence[str], None] = '3cf62fa2e52d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TestOrders', sa.Column('validated_by', sa.String(), nullable=True))
    op.add_column('TestOrders', sa.Column('validated_on', sa.TIMESTAMP(), nullable=True))
    op.add_column('TestOrders', sa.Column('validation_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TestOrders', 'validation_status')
    op.drop_column('TestOrders', 'validated_on')
    op.drop_column('TestOrders', 'validated_by')
    # ### end Alembic commands ###
