"""Sync schema

Revision ID: 693c3cf8aaa8
Revises: 37705d007c23
Create Date: 2025-07-22 10:34:46.294277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '693c3cf8aaa8'
down_revision: Union[str, Sequence[str], None] = '37705d007c23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CoastDownData',
    sa.Column('CoastDownData_id', sa.String(), nullable=False),
    sa.Column('job_order_id', sa.String(), nullable=True),
    sa.Column('coast_down_reference', sa.String(), nullable=True),
    sa.Column('vehicle_reference_mass', sa.Float(), nullable=True),
    sa.Column('a_value', sa.Float(), nullable=True),
    sa.Column('b_value', sa.Float(), nullable=True),
    sa.Column('c_value', sa.Float(), nullable=True),
    sa.Column('f0_value', sa.Float(), nullable=True),
    sa.Column('f1_value', sa.Float(), nullable=True),
    sa.Column('f2_value', sa.Float(), nullable=True),
    sa.Column('id_of_creator', sa.String(), nullable=True),
    sa.Column('created_on', sa.TIMESTAMP(), nullable=True),
    sa.Column('id_of_updater', sa.String(), nullable=True),
    sa.Column('updated_on', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('CoastDownData_id')
    )
    op.drop_column('JobOrders', 'mail_remarks')
    op.drop_column('JobOrders', 'rejection_remarks')
    op.drop_column('JobOrders', 'remarks')
    op.add_column('RDEJobOrders', sa.Column('requested_payload', sa.String(), nullable=True))
    op.add_column('RDEJobOrders', sa.Column('cft_members', sa.JSON(), nullable=True))
    op.drop_column('RDEJobOrders', 'mail_remarks')
    op.drop_column('RDEJobOrders', 'rejection_remarks')
    op.drop_column('RDEJobOrders', 'remarks')
    op.add_column('TestOrders', sa.Column('dataset_attachment', sa.JSON(), nullable=True))
    op.add_column('TestOrders', sa.Column('a2l_attachment', sa.JSON(), nullable=True))
    op.add_column('TestOrders', sa.Column('experiment_attachment', sa.JSON(), nullable=True))
    op.add_column('TestOrders', sa.Column('dbc_attachment', sa.JSON(), nullable=True))
    op.add_column('TestOrders', sa.Column('wltp_attachment', sa.JSON(), nullable=True))
    op.add_column('TestOrders', sa.Column('pdf_report', sa.JSON(), nullable=True))
    op.add_column('TestOrders', sa.Column('excel_report', sa.JSON(), nullable=True))
    op.add_column('TestOrders', sa.Column('dat_file_attachment', sa.JSON(), nullable=True))
    op.add_column('TestOrders', sa.Column('others_attachement', sa.JSON(), nullable=True))
    op.add_column('TestOrders', sa.Column('remarks', sa.String(), nullable=True))
    op.add_column('TestOrders', sa.Column('rejection_remarks', sa.String(), nullable=True))
    op.add_column('TestOrders', sa.Column('mail_remarks', sa.String(), nullable=True))
    op.alter_column(
    'TestOrders',
    'emission_check_attachment',
    type_=sa.JSON(),
    postgresql_using="emission_check_attachment::json"
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    pass
    # ### end Alembic commands ###
