"""create three new columns in TesOrders table name- rating(integer),rating_remarks(string),rated_by(stirng),rated_on(timestamp)

Revision ID: 7911586f68de
Revises: 623d55e59aa9
Create Date: 2025-08-20 17:05:50.726463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7911586f68de'
down_revision: Union[str, Sequence[str], None] = '623d55e59aa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TestOrders', sa.Column('rating', sa.Integer(), nullable=True))
    op.add_column('TestOrders', sa.Column('rating_remarks', sa.String(), nullable=True))
    op.add_column('TestOrders', sa.Column('rated_by', sa.String(), nullable=True))
    op.add_column('TestOrders', sa.Column('rated_on', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TestOrders', 'rated_on')
    op.drop_column('TestOrders', 'rated_by')
    op.drop_column('TestOrders', 'rating_remarks')
    op.drop_column('TestOrders', 'rating')
    # ### end Alembic commands ###
