"""add new column named gear_ratio_6 in table Vehicles

Revision ID: fc049a468833
Revises: 5ec265b526ef
Create Date: 2025-08-30 19:40:15.069128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc049a468833'
down_revision: Union[str, Sequence[str], None] = '5ec265b526ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Vehicles', sa.Column('gear_ratio_6', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Vehicles', 'gear_ratio_6')
    # ### end Alembic commands ###
