apiVersion: v1
kind: Service
metadata:
  name: {{ include "gto-projects.fullname" . }}
  labels:
    {{- include "gto-projects.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 4173
      protocol: TCP
      name: http
  selector:
    {{- include "gto-projects.selectorLabels" . | nindent 4 }}
